(in-package #:csnd)

(defopcode a func (x))
(defopcode abs~ func (x) "abs")
(defopcode active ugen (insnum &optional iopt))
(defopcode adsr ugen (iatt idec islev irel &optional idel))
(defopcode adsyn ugen (kamod kfmod ksmod ifilcod))
(defopcode adsynt2 ugen (kamp kcps iwfn ifreqfn iampfn icnt &optional iphs))
(defopcode aftouch ugen (&optional imin imax))
(defopcode alpass ugen (asig krvt ilpt &optional iskip insmps))
(defopcode alwayson command (tinstrument &rest pn))
(defopcode ampdb func (x))
(defopcode ampdbfs func (x))
(defopcode ampmidi ugen (iscal &optional ifn))
(defopcode ampmidid ugen (ivelocity idecibels))
(defopcode areson ugen (asig kcf kbw &optional iscl iskip))
(defopcode aresonk ugen (ksig kcf kbw &optional iscl iskip))
(defopcode atone ugen (asig khp &optional iskip))
(defopcode atonek ugen (ksig khp &optional iskip))
(defopcode atonex ugen (asig khp &optional inumlayer iskip))
(defopcode ats-add ugen (ktimepnt kfmod iatsfile ifn ipartials
				  &optional ipartialoffset ipartialincr igatefn)
    "ATSadd")

(defopcode ats-addnz ugen (ktimepnt iatsfile ibands &optional ibandoffset ibandincr)
    "ATSaddnz")

(defopcode ats-bufread command (ktimepnt kfmod iatsfile ipartials &optional
					 ipartialoffset ipartialincr)
    "ATSbufread")

(defopcode ats-cross ugen (ktimepnt kfmod iatsfile ifn kmylev kbuflev ipartials
				    &optional ipartialoffset ipartialincr)
    "ATScross")

(defopcode ats-info ugen (iatsfile ilocation) "ATSinfo")
(defopcode ats-interpread ugen (kfreq) "ATSinterpread")
(defopcode ats-read ugen (ktimepnt iatsfile ipartial) "ATSread")
(defopcode ats-readnz ugen (ktimepnt iatsfile iband) "ATSreadnz")
(defopcode ats-partialtap ugen (ipartialnum) "ATSpartialtap")
(defopcode ats-sinnoi ugen (ktimepnt ksinlev knzlev kfmod iatsfile ipartials
				     &optional ipartialoffset ipartialincr)
    "ATSsinnoi")

(defopcode babo ugen (asig ksrcx ksrcy ksrcz irx iry irz
			   &optional idiff ifno))
(defopcode balance ugen (asig acomp &optional ihp iskip))
(defopcode bamboo ugen (kamp idettack &optional inum idamp imaxshake ifreq ifreq1 ifreq2))
(defopcode barmodel ugen (kbcl kbcr ik ib kscan it30 ipos ivel iwid))
(defopcode bbcutm ugen (asource ibps isubdiv ibarlength iphrasebars inumrepeats
				&optional istutterspeed istutterchance ienvchoice))
(defopcode bbcuts ugen (asource1 asource2 ibps isubdiv ibarlength iphrasebars inumrepeats
				 &optional istutterspeed istutterchance ienvchoice))
(defopcode betarand ugen (krange kalpha kbeta))
(defopcode bexprnd ugen (krange))
(defopcode bformenc1 ugen (asig kalpha kbeta))
(defopcode bformdec1 ugen (isetup aw ax ay az &optional ar as at au av abk al am an ao ap aq))
(defopcode binit ugen (fin isize))
(defopcode biquad ugen (asig kb0 kb1 kb2 ka0 ka1 ka2 &optional iskip))
(defopcode biquada ugen (asig ab0 ab1 ab2 aa0 aa1 aa2 &optional iskip))
(defopcode birnd func (x))
(defopcode bqrez ugen (asig xfco xres &optional imode iskip))
(defopcode butbp ugen (asig kfreq kband &optional iskip))
(defopcode butbr ugen (asig kfreq kband &optional iskip))
(defopcode buthp ugen (asig kfreq &optional iskip))
(defopcode butlp ugen (asig kfreq &optional iskip))
(defopcode buzz ugen (xamp xcps knh ifn &optional iphs))


(defopcode cabasa ugen (iamp idettack &optional inum idamp imaxshake))
(defopcode cauchy ugen (kalpha))
(defopcode cauchyi ugen (klambda xamp xcps))
(defopcode ceil func (x))
(defopcode cell command (ktrig kreinit ioutfunc initstatefunc irulefunc ielements))
(defopcode cent func (x))
(defopcode centroid ugen (asig ktrig ifftsize))
(defopcode cggoto command (condition label))
(defopcode chanctrl ugen (ichnl ictlno &optional ilow ihigh))
(defopcode changed ugen (kval1 &rest kn))
(defopcode chani ugen (kchan))
(defopcode chano command (kval kchan))
(defopcode chebyshevpoly ugen (ain k0 &rest kn))
(defopcode chn_k command (sname imode &optional itype idflt imin imax))
(defopcode chn_a command (sname imode))
(defopcode chn_s command (sname imode) "chn_S")
(defopcode chnclear command (sname))
(defopcode chnexport ugen (sname imode &optional itype idflt imin imax))
(defopcode chnget ugen (sname))
(defopcode chnmix command (aval sname))
;chnparams
(defopcode chnrecv ugen (sname))
(defopcode chnsend command (ival sname))
(defopcode chnset command (ival sname))
(defopcode chuap ugen (kl kr0 kc1 kg kga kgb ke kc2 il3 iv2 iv1 ktime_step))
(defopcode cigoto command (condition label))
(defopcode ckgoto command (ckgoto label))
(defopcode clear command (aval1 &rest avaln))
(defopcode clfilt ugen (asig kfreq itype inpol &optional ikind ipbr isba iskip))
(defopcode clip ugen (asig imeth ilimit &optional iarg))
(defopcode clockoff command (inum))
(defopcode clockon command (inum))
(defopcode cngoto command (condition label))
(defopcode comb ugen (asig krvt ilpt &optional iskip insmps))
(defopcode combinv ugen (asig krvt ilpt &optional iskip insmps))
(defopcode compress ugen (aasig acsig kthresh kloknee khiknee kratio katt krel ilook))
(defopcode connect command (tsource1 soulet1 tsink1 sinlet1))
(defopcode convolve ugen (ain ifilcod &optional ichannel))
(defopcode copya2ftab command (tab kftbl))
(defopcode copyf2array command (tab kftbl))
(defopcode cos~ func (x) "cos")
(defopcode cosseg ugen (ia idur1 ib &rest rest))
(defopcode cossegb ugen (ia itim1 ib &rest rest))
;;cossegr
(defopcode cosh~ func (x) "cosh")
(defopcode cosinv func (x))
(defopcode cps2pch ugen (ipch iequal))
(defopcode cpsmidi ugen nil)
(defopcode cpsmidib ugen (&optional irange))
(defopcode cpsmidinn func (midinote))
(defopcode cpsoct func (oct))
(defopcode cpspch func (pch))
(defopcode cpstmid ugen (ifn))
(defopcode cpstun ugen (ktrig kindex kfn))
(defopcode cpstuni ugen (index ifn))
(defopcode cpsxpch ugen (ipch iequal irepeat ibase))
(defopcode cpumeter ugen (ifreq))
(defopcode cpuprc command (insnum ipercent))
(defopcode cross2 ugen (ain1 ain2 isize ioverlap iwin kbias))
(defopcode crossfm ugen (xfrq1 kfrq1 xndx1 xndx2 kcps ifn1 ifn2 &optional iphs1 iphs2))
(defopcode crossfmi ugen (xfrq1 xfrq2 xndx1 xndx2 kcps ifn1 ifn2 &optional iphs1 iphs2))
(defopcode crosspm ugen (xfrq1 xfrq2 xndx1 xndx2 kcps ifn1 ifn2 &optional iphs1 iphs2))
(defopcode crosspmi ugen (xfrq1 xfrq2 xndx1 xndx2 kcps ifn1 ifn2 &optional iphs1 iphs2))
(defopcode crossfmpm ugen (xfrq1 xfrq2 xndx1 xndx2 kcps ifn1 ifn2 &optional iphs1 iphs2))
(defopcode crossfmpmi ugen (xfrq1 xfrq2 xndx1 xndx2 kcps ifn1 ifn2 &optional iphs1 iphs2))
(defopcode crunch ugen (iamp idettack &optional inum idamp imaxshake))
(defopcode ctrl14 ugen (ichan ictlno1 ictrlno2 imin imax &optional ifn))
(defopcode ctrl21 ugen (ichan ictlno1 ictrlno2 ictlno3 kmin kmax &optional ifn))
(defopcode ctrl7 ugen (ichan ictlno kmin kmax &optional ifn icutoff))
(defopcode ctrlinit command (ichnl ictlno1 ival1 &rest rest))
(defopcode cuserrnd ugen (min kamx ktablenum))
