(in-package #:csound)

(defopcode dam ugen (asig kthreshold icomp1 icomp2 irtime iftime))
(defopcode date ugen nil)
(defopcode dates ugen (&optional itime))
(defopcode db func (x))
(defopcode dbamp func (x))
(defopcode dbfsamp func (x))
(defopcode dcblock ugen (ain &optional igain))
(defopcode dcblock2 ugen (ain &optional iorder iskip))
(defopcode dconv ugen (asig isize ifn))
(defopcode delay ugen (asig idlt &optional iskip))
(defopcode delay1 ugen (asig &optional iskip))
(defopcode delayk ugen (ksig idel &optional imode))
(defopcode vdel_k ugen (ksig kdel imdel &optional imode))
(defopcode delayr ugen (idlt &optional iskip))
(defopcode delayw command (asig))
(defopcode deltap ugen (kdlt))
(defopcode deltap3 ugen (xdlt))
(defopcode deltapi ugen (xdlt))
(defopcode deltapn ugen (xnumsamps))
(defopcode deltapx ugen (adel iwsize))
(defopcode deltapxw command (ain adel iwsize))
(defopcode denorm command (a1 &rest rest))
(defopcode diff ugen (asig &optional iskip))
(defopcode diskgrain ugen (sfname kamp kfreq kpitch kgrsize kprate ifun iolaps &optional imaxgrsize ioffset))
(defopcode diskin2 ugen (ifilcod kpitch &optional iskiptim iwrap iformat iwsize ibufsize iskipinit))
;; dispfft
;; display
(defopcode distort ugen (asig kdist ifn &optional ihp istor))
(defopcode distort1 ugen (asig kpregain kpostgain kshape1 kshape2 &optional imode))
(defopcode divz ugen (xa xb ksubst))
(defopcode doppler ugen (asource ksourceposition kmicposition &optional isoundspeed ifiltercutoff))
(defopcode downsamp ugen (asig &optional iwlen))
(defopcode dripwater ugen (kamp idettack &optional inum idamp imaxshake ifreq ifreq1 ifreq2))
(defopcode dumpk command (ksig ifilname iformat iprd))
(defopcode dumpk2 command (ksig1 ksig2 ifilname iformat iprd))
(defopcode dumpk3 command (ksig1 ksig2 ksig3 ifilname iformat iprd))
(defopcode dumpk4 command (ksig1 ksig2 ksig3 ksig4 ifilname iformat iprd))
(defopcode duserrnd ugen (ktablenum))
(defopcode dust ugen (kamp kdensity))
(defopcode dust2 ugen (kamp kdensity))

(defopcode envlpx ugen (xamp irise idur idec ifn iatss iatdec &optional ixmod))
(defopcode envlpxr ugen (xamp irise idec ifn iatss iattdec &optional ixmod irind))
(defopcode eqfil ugen (ain kcf kbw kgain &optional istor))
(defopcode event command (scorechar kinsnum kdelay kdur &rest pn))
(defopcode event-i command (scorechar iinsnum idelay idur &rest pn) "event_i")
;;; exitnow
(defopcode exp~ func (x) "exp")
(defopcode expcurve ugen (kindex ksteepness))
(defopcode expon ugen (ia idur ib))
(defopcode exprand ugen (klambda))
(defopcode exprandi ugen (klmabda xamp xcps))
(defopcode expseg ugen (ia idur1 ib &rest pn))
(defopcode expsega ugen (ia idur1 ib &rest pn))
(defopcode expsegb ugen (ia idur1 ib &rest pn))
(defopcode expsegba ugen (ia idur1 ib &rest pn))
(defopcode expsegr ugen (ia idur1 ib &rest pn))

;;; ficlose
(defopcode filebit ugen (ifilcod &optional iallowraw))
(defopcode filelen ugen (ifilcod &optional iallowraw))
(defopcode filenchnls ugen (ifilcod &optional iallowraw))
(defopcode filepeak ugen (ifilcod &optional ichnl))
(defopcode filesr ugen (ifilcod &optional iallowraw))
(defopcode filevalid ugen (ifilcod))
(defopcode filter2 ugen (asig im in ib0 ib1 &rest rest))
(defopcode fin command (ifilename iskipframes iformat ain1 &rest rest))
(defopcode fini command (ifilename iskipframes iformat in1 &rest rest))
(defopcode fink command (ifilename iskipframes iformat kin1 &rest rest))
;;; fiopen
(defopcode flanger ugen (asig adel kfeedback &optional imaxd))
(defopcode flashtxt command (iwhich string))
(defopcode flooper ugen (kamp kpitch istart idur ifad ifn))
(defopcode flooper2 ugen (kamp kpitch kloopstart kloopend kcrossfade ifn &optional istart imode ifenv iskip))
(defopcode floor~ func (x) "floor")
(defopcode fmb3 ugen (kamp kfreq kc1 kc2 kvdepth kvrte ifn1 ifn2 ifn3 ifn4 ivfn))
(defopcode fmbell ugen (kamp kfreq kc1 kc2 kvdepth kvrate ifn1 ifn2 ifn3 ifn4 ivfn &optional isus))
(defopcode fmmetal ugen (kamp kfreq kc1 kc2 kvdepth kvrate ifn1 ifn2 ifn3 ifn4 ivfn))
(defopcode fmpercfl ugen (kamp kfreq kc1 kc2 kvdepth kvrate ifn1 ifn2 ifn3 ifn4 ivfn))
(defopcode fmrhode ugen (kamp kfreq kc1 kc2 kvdepth kvrate ifn1 ifn2 ifn3 ifn4 ivfn))
(defopcode fmvoice ugen (kamp kfreq kvowel ktilt kvibamt kvibrate ifn1 ifn2 ifn3 ifn4 ivibfn))
(defopcode fmwurlie ugen (kamp kfreq kc1 kc2 kvdepth kvrate ifn1 ifn2 ifn3 ifn4 ivfn))
(defopcode fof ugen (xamp xfund xform koct kband kris kdur kdec iolaps ifna ifnb itotdur &optional iphs ifmode iskip))
(defopcode fof2 ugen (xamp xfund xform koct kband kris kdur kdec iolaps ifna ifnb itotdur kphs kgliss &optional iskip))
(defopcode fofilter ugen (ain kcf kris idec &optional istor))
(defopcode fog ugen (xamp xdens xtrans aspd koct kband kris kdur kdec iolaps ifna ifnb itotdur &optional iphs itmode iskip))
(defopcode fold ugen (asig kincr))
(defopcode follow ugen (asig idt))
(defopcode follow2 ugen (asig katt krel))
(defopcode foscil ugen (xamp kcps xcar xmod kndx ifn &optional iphs))
(defopcode foscili ugen (xamp kcps xcar xmod kndx ifn &optional iphs))
(defopcode fout command (ifilename iformat aout1 &rest aoutn))
(defopcode fout-i command (ihandle iformat iflag iout1 &rest ioutn) "fouti")
(defopcode fout-ir command (ihandle iformat iflag iout1 &rest ioutn) "foutir")
(defopcode fout-k command (ifilename iformat kout1 &rest koutn) "foutk")
(defopcode fprintks command (filename string &rest kvaln))
;;; fprints
(defopcode frac func (x))
(defopcode fractalnoise ugen (kamp kbeta)) 
(defopcode freeverb ugen (ain-l ain-r kroomsize khfdamp &optional israte iskip))
(defopcode ftchnls func (x))
(defopcode ftconv ugen (ain ift iplen &optional iskipsamples iirlen iskipinit))
(defopcode ftcps fun (x))
(defopcode ftfree command (ifno iwhen))
(defun ftgen (ifn itime isize igen iarga &rest iargn)
  (make-instance 'gen-routine :ifn ifn 
			      :args (list ifn itime isize igen iarga)
			      :opt-args (remove nil iargn)
			      :name "ftgen"))

(export 'ftgen)


;;; ftgenonce
;;; ftgentmp
(defopcode ftlen func (x))
;;; ftload
;;; ftloadk
(defopcode ftlptim func (x))
(defopcode ftmorf command (kftndx iffn iresfn))
;;; ftsave
;;; ftsavek
(defopcode ftsr func (x))


 
