(in-package #:csound)
;;; jack...
(defopcode jitter ugen (kamp kcpsmin kcpsmax))
(defopcode jitter2 ugen (ktotamp kamp1 kcps1 kamp2 kcps2 kamp3 kcps3))
(defopcode jspline ugen (kamp kcpsmin kcpsmax))
(defopcode k func (x))

(defopcode kgoto command (label))
(defopcode lfo ugen (kamp kcps &optional itype))
(defopcode limit ugen (asig klow khigh))
(defopcode line ugen (ia idur ib))
(defopcode linen ugen (xamp irise idur idec))
(defopcode linenr ugen (xamp irise idec iatdec))
(defopcode lineto ugen (ksig ktime))
(defopcode linrand ugen (krange))
(defopcode linseg ugen (ia idur1 ib &rest rest))
(defopcode linsegb ugen (ia idur1 ib &rest rest))
(defopcode linsegr ugen (ia idur1 ib &rest rest))
(defopcode locsend ugen nil)
(defopcode locsig ugen (asig kdegree kdistance kreverbsend))
(defopcode log~ func (x) "log")
(defopcode log10 func (x))
(defopcode log2 func (x))
(defopcode logbtwo func (x))
(defopcode logcurve ugen (kindex ksteepness))
(defopcode loop-ge command (kdnx kdecr kmin label) "loop_ge")
(defopcode loop-gt command (kdnx kdecr kmin label) "loop_gt")
(defopcode loop-le command (kndx kncr kmax label) "loop_le")
(defopcode loop-lt command (kndx kncr kmax label) "loop_lt")
(defopcode loopseg ugen (kfreq ktrig iphase ktime0 kvalue0 &rest rest))
(defopcode loopsegp ugen (kphase kvalue0 kdur0 kvalue1 &rest rest))
(defopcode looptseg ugen (kfreq ktrig ktime0 kvalue0 ktype0 &rest rest))
(defopcode loopxseg ugen (kfreq ktrig iphase ktime0 kvalue0 &rest rest))
(defopcode lorenz ugen (ksv krv kbv kh ix iy iz iskip &optional iskipinit))
(defopcode lorisread command (ktimpnt ifilcod istoreidx kfreqenv kampenv kbwenv &optional ifadetime))
(defopcode lorismorph command (isrcidx itgtidx istoreidx kfreqmorphenv kampmorphenv kbwmorphenv))
(defopcode lorisplay ugen (ireadidx kfreqenv kampenv kbwenv))
(defopcode loscil ugen (xamp kcps ifn &optional ibas imod1 ibeg1 iend1 imod2 ibeg2 iend2))
(defopcode loscil3 ugen (xamp kcps ifn &optional ibas imod1 ibeg1 iend1 imod2 ibeg2 iend2))
(defopcode loscilx ugen (xamp kcps ifn &optional iwsize ibas istrt imod1 ibeg1 iend1))
(defopcode lowpass2 ugen (asig kcf kq &optional iskip))
(defopcode lowres ugen (asig kcutoff kresonance &optional iskip))
(defopcode lowresx ugen (aisg kcutoff kresonance &optional inumlayer iskip))
(defopcode lpf18 ugen (asig kfco kres kdist &optional iskip))
(defopcode lpfreson ugen (ais gkfreqratio))
(defopcode lphasor ugen (xtrns &optional ilps ilpe imode istrt istor))
(defopcode lpinterp command (islot1 islot2 kmix))
(defopcode lposcil ugen (kamp kfreqratio kloop kend ifn &optional iphs))
(defopcode lposcil3 ugen (kamp kfreqratio kloop kend ifn &optional iphs))
(defopcode lposcila ugen (aamp freqratio kloop kend ift &optional iphs))
(defopcode lposcilsa ugen (aamp kfreqratio kloop kend ift &optional iphs))
(defopcode lposcilsa2 ugen (aamp kfreqratio kloop kend ift &optional iphs))
(defopcode lpread ugen (ktimpnt ifilcod &optional inpoles ifrmrate))
(defopcode lpreson ugen (asig))
(defopcode lpshold ugen (kfreq ktrig iphase itime0 kvalue0 &rest rest))
(defopcode lpsholdp ugen (kphase ktrig ktime0 kvalue0 &rest rest))
(defopcode lpslot command (islot))
;;; lua
