(in-package #:csnd)

;;; p opcodes
(defopcode p func (x))
(defopcode pan2 ugen (asig xp &optional imode))
(defopcode pan ugen (asig kx ky ifn &optional imode ioffset))
(defopcode pareq ugen (asig kc kq &optional imoe iskip))
(defopcode partials ugen (ffr fphs kthresh kminpts kmaxgap imaxtracks))
;;; partikkel
(defopcode pcauchy ugen (kalpha))
(defopcode pchmidinn func (midinote))
(defopcode pchoct func (oct))
(defopcode pconvolve ugen (asin ifilcod &optional ipartitionsize ichannel))
(defopcode pdclip ugen (ain kwidth kcenter &optional ibipolar ifullscale))
(defopcode pdhalf ugen (ain kshape-amount &optional ibipolar ifullscale ))
(defopcode pdhalfy ugen (ain kshape-amount &optional ibipolar ifullscale))
(defopcode peak ugen (asig))
(defopcode phaser1 ugen (asig kfreq kord kfeedback &optional iskip))
(defopcode pahser2 ugen (asig kfreq kq kord kmode ksep kfeedback))
(defopcode phasor ugen (xcps &optional iphs))
(defopcode phasorbnk ugen (xcps kndx icnt &optional iphs))
(defopcode pinkish ugen (xin &optional imethod inumbands iseed iskip))
(defopcode pitch ugen (asig iupdate ilo ihi idbthresh &optional ifrqs iconf
			    istrt iocts iq inptls irolloff iskip))
(defopcode pitchamdf ugen (asig imincps imaxcps &optional icps imedi idowns iexcps irmsmedi))
(defopcode planet ugen (kmass1 kmass2 ksep ix iy iz ivx ivy ivz idelta &optional ifriction iskip))
(defopcode platerev ugen (itabexcite  itabouts kbndry iaspect istiff idecay iloss aexcite1
				      &rest aexcite2))
(defopcode plltrack ugen (asig kd &optional kloof kllopq klf khf kthresh))
(defopcode pluck ugen (kamp kcps icps ifn imeth &optional iparm1 iparm2))
(defopcode plustab ugen (tleft tright))
(defopcode poisson ugen (klambda))
(defopcode polynomial ugen (ain k0 &rest kn))
(defopcode pop~ ugen nil "pop")
(defopcode pop-f ugen nil "pop_f")
(defopcode port ugen (ksig ihtim &optional isig))
(defopcode portk ugen (ksig khtim &optional isig))
(defopcode poscil3 ugen (kamp kcps ifn &optional iphs))
(defopcode poscil ugen (aamp acps ifn &optional ipns))
(defopcode pow ugen (aarg kpow &optional inorm))
(defopcode powershape ugen (ain kshapeamount &optional ifullscale))
(defopcode powoftwo func (x))
(defopcode prepiano ugen (ifreq ins id ik it30 ib kbcl kbcr imass ifreq2 iinit ipos ivel isfreq isspread &optional irattles irubbers))
(defopcode print~ command (iarg &rest iargn) "print")
(defopcode printf command (sfmt ktrig &rest xarg))
(defopcode printk2 command (kvar &optional inumspaces))
(defopcode printk command (itime kval &optional ispace))
(defopcode printks command (string itime &optional kvals))
(defopcode prints command (string &rest kvals))
(defopcode product ugen (asig1 asig2 &rest asign))
(defopcode ptrack ugen (asig ihopsize &optional ipeaks))
(defopcode push~ command (xval &rest xvals) "push")
(defopcode push-f command (fsig) "push_f")
(defopcode puts command (sstr ktrig &optional inonl))

(defopcode pvadd ugen (ktimpnt kfmod ifilcod ifn ibins &optional ibinoffset ibinincr iextractmode ifreqlim igatefn))
(defopcode pvbufread command (ktimpnt ifile))
(defopcode pvcross ugen (ktimpnt kfmod ifile kampscale1 kampscale2 &optional ispecwp))
(defopcode pvinterp ugen (ktimpnt kfmod ifile kfreqscale1 kfreqscale2 kampscale1 kampscale2 kfreqinterp kampinterp))
(defopcode pvoc ugen (ktimpnt kfmod ifilcod &optional ispecwp iextractmode ifreqlim igatefn))
(defopcode pvread ugen (ktimpnt ifile ibin))
(defopcode pvsadsyn ugen (fsrc inoscs kfmod &optional ibinoffset ibinincr iinit))
(defopcode pvsanal ugen (ain ifftsize iverlap iwinsize iwintype &optional iformat iinit))
(defopcode pvsarp ugen (fsigin kbin kdepth kgain ))
(defopcode pvsbandp ugen (fsigin xlowcut xlowfull xhighfull xhighcut &optional ktype))
(defopcode pvsbandr ugen (fsigin xlowcut xlowfull xhighfull xhighcut &optional ktype))
(defopcode pvsbin ugen (fsig kbin))
(defopcode pvsblur ugen (fsigin kblurtime imaxdel))
(defopcode pvsbuffer ugen (fsig ilen))
(defopcode pvsbufread ugen (ktime khandle &optional ilo ihi iclear))
(defopcode pvsbufread2 ugen (ktime khandle ift1 ift2))
(defopcode pvscale ugen (ksigin kscal &optional kkeepform kgain kcoefs))
(defopcode pvscent ugen (fsig))
(defopcode pvscross ugen (fsrc fdest kamp1 kamp2))
(defopcode pvsdemix ugen (fleft fright kpos kwidth ipoints))
(defopcode pvsdiskin ugen (sfname ktscal kgain &optional ioffset ichan))
(defopcode pvsdisp command (fsig &optional ibins iwtflg))
(defopcode pvsfilter ugen (fsigin fsigfil kdepth &optional igain))
(defopcode pvsfread ugen (ktimpt ifn &optional ichan))
(defopcode pvsfreeze ugen (fsigin kfreez kfreezf))
(defopcode pvsftr command (fsrc ifna &optional ifnf))
(defopcode pvsftw ugen (fsrc ifna &optional ifnf))
(defopcode pvsfwrite command (fsig ifile))
(defopcode pvsgain ugen (fsigin kgain))
(defopcode pvshift ugen (fsigin kshift klowest &optional kkeepform igain kcoefs))
(defopcode pvsifd ugen (ain ifftsize ihopsize iwintype &optional iscal))
(defopcode pvsinfo ugen (fsrc))
(defopcode pvsinit ugen (isize &optional iolap iwinsize iwintype iformat))
(defopcode pvsin ugen (kchan &optional isize iolap iwinsize iwintype iformat))
(defopcode pvslock ugen (fsigin klock))
(defopcode pvsmaska ugen (fsrc ifn kdepth))
(defopcode pvsmix ugen (fsigin1 fisgin2))
(defopcode pvsmorph ugen (fsig1 fsig2 kampint kfrqint))
(defopcode pvsmooth ugen (fsigin kacf kfcf))
(defopcode pvsout command (fsig kchan))
(defopcode pvsosc ugen (kamp kfreq ktype isize &optional ioverlap iwinsize iwintype iformat))
(defopcode pvspitch ugen (fsig kthresh))
(defopcode pvstanal ugen (ktimescal kamp kpitch ktab &optional kdetect kwrap ioffset ifftsize ihop idbthresh))
(defopcode pvstencil ugen (fsigin kgain klevel iftable))
(defopcode pvsvoc ugen (famp fexc kdepth kgain &optional kcoefs))
(defopcode pvsynth ugen (fsrc &optional iinit))
(defopcode pvswarp ugen (fsigin kscal kshift &optional klowest kmeth kgain kcoefs))
(defopcode pvs2tab ugen (tvar fsig))


;;; q opcodes
(defopcode qinf func (x))
(defopcode qnan func (x))

;;; r opcodes
(defopcode rand ugen (xamp &optional iseed isel ioffset))
(defopcode randh ugen (xamp xcps &optional iseed isize ioffset))
(defopcode randi ugen (xamp xcps &optional iseed isize ioffset))
(defopcode random~ ugen (kmin kmax) "random")
(defopcode randomh ugen (kmin kmax xcps &optional imode ifirstval))
(defopcode randomi ugen (kmin kmax kcps &optional imode ifirstval))
(defopcode rbjeq ugen (asig kfco klvl kq ks &optional imode))
(defopcode readclock ugen (inum))
(defopcode readf ugen (ifilename))
(defopcode reinit command (label))
(defopcode release ugen nil)
(defopcode remove~ command (insnum) "remove")
(defopcode repluck ugen (iplk kamp icps kpick krefl axcite))
(defopcode reson ugen (asig kcf kbw &optional iscl iskip))
(defopcode resonk ugen (ksig kcf kbw &optional iscl iskip))
(defopcode resonr ugen (asig kcf kbw &optional iscl iskip))
(defopcode resonx ugen (asig kcf kbw &optional inumlayer iscl iskip))
(defopcode resonxk ugen (ksig kcf kbw &optional inumlayer iscl istor))
(defopcode resony ugen (asig kbf kbw inum ksep &optional isepmode iscl iskip))
(defopcode resonz ugen (asig kcf kbw &optional iscl iskip))
(defopcode resyn ugen (fin kscal kpitch kmaxtracks ifn))
(defopcode reverb ugen (asig krvt &optional iskip))
(defopcode reverb2 ugen (asig ktime khdif &optional iskip inumcombs ifn combs inumalpas ifnalpas))
(defopcode reverbsc ugen (ain-l ain-r kfblvl kfco &optional israte ipitchm iskip))
(defopcode rezzy ugen (asig xfco xres &optional imode iskip))
(defopcode rigoto command (label))
(defopcode rireturn command nil)
(defopcode rms ugen (asig &optional ihp iskip))
(defopcode rnd func (x))
(defopcode rnd31 ugen (kscl krpow &optional iseed))
(defopcode round~ func (x) "round")
(defopcode rspline ugen (xrange-min xrange-max kcps-min kcps-max))
(defopcode rtclock command nil)


