(in-package #:csound)
(defopcode samphold ugen (asig agate &optional ival ivstor))
(defopcode sandpaper ugen (iamp idettack &optional inum idamp imaxshake))
(defopcode scale ugen (kinput kmax kmin))
(defopcode scalearray command (tarray kmin kmax &optional kleft kright))
(defopcode scanhammer command (isrc idst ipos imult))
(defopcode scans ugen (kamp kfreq ifn id &optional iorder))
(defopcode scantable ugen (kamp kpch ipos imass istiff idamp ivel))
(defopcode scanu command (init irate ifnvel ifnmass ifnstif ifncentr ifndamp kmass
							   kstif kcentr kdamp ileft iright kpos kstrngth ain idisp id))
(defopcode schedkwhen command (ktrigger kmintim kmaxnum kinsnum kwhen kdur &rest ipn))
(defopcode schedkwhennamed command (ktrigger kmintim kmaxnum sname kwhen kdur &rest ipn))
(defopcode schedule command (insnum iwhen idur &rest ipn))
(defopcode schedwhen command (ktrigger kinsnum kwhen kdur &rest ipn))
(defopcode seed command (ival))
(defopcode sekere ugen (iamp idettack &optional inum idamp imaxshake))
(defopcode shaker ugen (kamp kfreq kbeans kdamp ktimes &optional idecay))
(defopcode signum~ func (x))
(defopcode sin~ func (x) "sin")
(defopcode sinh~ func (x) "sinh")
(defopcode sininv func (x))
(defopcode sinsyn ugen (fin kscal kmaxtrakcs ifn))
(defopcode sleighbells ugen (kamp idettack &optional inum idamp imaxshake ifreq ifreq1 ifreq2))


(defopcode sndload command (sfname &optional ifmt ichns isr ibas iamp istrt ilpmod ilps ilpe))
(defopcode sndloop ugen (ain kpitch ktrig idur ifad))
(defopcode sndwarp ugen (xamp xtimewarp xresample ifn1 ibeg iwsize irandw ioverlap ifn2 itimemode))
(defopcode sndwarpst ugen (xamp xtimewarp xresample ifn1 ibeg iwsize irandw ioverlap ifn2 itimemode))
(defopcode soundin ugen (ifilcod iskptim iformat iskipinit ibufsize))
(defopcode space ugen (asig ifn ktime kreverbsend kx ky))
(defopcode spat-3d ugen (ain kx ky kz idist ift imode imodel iovr &optional istor) "spat3d")
(defopcode spat-3di ugen (ain ix iy iz idist ift imode &optional istor) "spat3di")
(defopcode spat-3dt command (ioutft ix iy iz idist ift imode irlen &optional iftnocl))

(defopcode specaddm ugen (wsig1 wsig2 &optional imul2))
(defopcode specdiff ugen (wsigin))
(defopcode specfilt ugen (wsigin ifhtim))
(defopcode spechist ugen (wsigin))
(defopcode specptrk ugen (wsig kvar ilo ihi istr idbthresh inptls irolloff
							   &optional iodd iconfs interp ifprd iwtflg))
(defopcode specscal ugen (wsigin ifscale ifthresh))
(defopcode specsum ugen (wsig &optional interp))
(defopcode spectrum ugen (xsig iprd iocts ifrqa &optional iq ihann idbout idsprd idsinrs))
(defopcode splitrig command (ktrig kndx imaxtics ifn kout1 &rest koutn))
(defopcode spsend command nil)
(defopcode sqrt~ func (x))
(defopcode stack command (istacksize))
(defopcode statevar ugen (ain kcf kq &optional iosamps istor))
(defopcode stix ugen (iamp idettack &optional inum idamp imaxshake))
(defopcode streson ugen (asig kfr ifdbgain))
(defopcode subinstr ugen (instrnum &rest pn))
(defopcode subinstrinit command (instrnum &rest pn))
(defopcode sum ugen (asig1 &rest asign))
(defopcode sumarray ugen (karray))
(defopcode svfilter ugen (asig kcf kq &optional iscl))
(defopcode syncgrain ugen (kamp kfreq kpitch kgrsize kprate ifun1 ifun2 iolaps))
(defopcode syncloop ugen (kamp kfreq kpitch kgrsize kprate klstart klend ifun1 ifun2 iolaps &optional istart iskip))
(defopcode syncphasor ugen (xcps asyncin &optional iphs))
(defopcode slicearray ugen (kinarray istart iend))


(defopcode tab-i ugen (index ifn &optional ixmode) "tab_i")
(defopcode tab ugen (xndx ifn &optional ixmode))
(defopcode tabw-i command (isig index ifn &optional ixmode) "tabw_i")
(defopcode tabw command (xsig xndx ifn &optional ixmode))
(defopcode tabrec command (ktrig_start ktrig_stop knumtics kfn kin1 &rest kinn))

(defopcode table ugen (xndx ifn &optional ixmode ixoff iwrap))
(defopcode table3 ugen (xndx ifn &optional ixmode ixoff iwrap))
(defopcode tablecopy command (kdft ksft))
(defopcode tablefilter ugen (kouttable kintable kmode kparam))
(defopcode tablefilteri ugen (iouttable iintable imode iparam))
(defopcode tablegpw command (kfn))
(defopcode tablei ugen (xndx ifn &optional ixmode ixoff iwrap))
(defopcode tableicopy command (idft isft))
(defopcode tableigpw command (ifn))
(defopcode tableikt ugen (xndx kfn &optional ixmode ixoff iwrap))
(defopcode tableimix command (idft idoff ilen is1ft is1off is1g is2ft is2off is2g))
(defopcode tableiw command (isig indx ifn &optional ixmode ixoff iwgmode))
(defopcode tablekt ugen (xndx kfn &optional ixmode ixoff iwrap))
(defopcode tablemix command (kdft kdoff klen ks1ft ks1off ks1g ks2ft ks2off ks2g))
(defopcode tableng ugen (xfn))
(defopcode tablera ugen (kfn kstart koff))
(defopcode tableseg command (ifn1 idur1 ifn2 &rest idur2))
(defopcode tableshuffle command (ktablenum))
(defopcode tableshufflei command (itablenum))
(defopcode tablew command (xsig xndx ifn &optional ixmode ixoff iwgmode))
(defopcode tablewa ugen (kfn asig koff))
(defopcode tablewkt command (xsig xndx kfn &optional ixmode ixoff iwgmode))
(defopcode tablexkt ugen (xndx kfn kwarp iwsize &optional ixmode ixoff iwrap))
(defopcode tablexseg command (ifn1 idur1 ifn2 &rest idur2))
(defopcode maparray ugen (kinarray string))
(defopcode maparray-i ugen (kinarray string) "maparray_i")
(defopcode tabmorph ugen (kindex kweightpoint ktabnum1 ktabnum2 ifn1 ifn2 &rest ifnn))
(defopcode tabmorpha ugen (aindex aweightpoint atabnum1 atabnum2 ifn1 ifn2 &rest ifnn))
(defopcode tabmorphk ugen (aindex kweightpoint ktabnum1 ktabnum2 ifn1 ifn2 &rest ifnn))
(defopcode tabmorphi ugen (kindex kweightpoint ktabnum1 ktabnum2 ifn1 ifn2 &rest ifnn))
(defopcode tabplay command (ktrig knumtics kfn kout1 &rest koutn))
(defopcode tabsum ugen (ifn kmin kmax))
(defopcode tab2pvs ugen (tvar &optional ihopsize iwinsize iwintype))
(defopcode tambourine ugen (kamp idettack &optional inum idamp imaxshake ifreq ifreq1 ifreq2))
(defopcode tan~ func (x) "tan")
(defopcode tanh~ func (x) "tanh")
(defopcode taninv func (x))
(defopcode taninv2 ugen (xy xx))
(defopcode tbvcf ugen (asig xfco xres kdist kasym &optional iskip))
(defopcode tempest ugen (kin iprd imindur imemdur ihp ithresh ihtim ixfdbak istartempo ifn
							 &optional idisprd itweek))
(defopcode tempo command (ktempo istartempo))
(defopcode temposcal ugen (ktimescal kamp kpitch ktab klock &optional ifftsize idecim ithresh))
(defopcode tempoval ugen nil)
(defopcode tigoto command (label))
(defopcode timedseq ugen (ktimpnt ifn kp1 &rest kpn))
(defopcode timeinstk ugen nil)
(defopcode timeinsts ugen nil)
(defopcode timek ugen nil)
(defopcode times ugen nil)
(defopcode timout command (istrt idur label))
(defopcode tival ugen nil)
(defopcode tlineto ugen (ksig ktime ktrig))
(defopcode tone ugen (asig khp &optional iskip))
(defopcode tonek ugen (ksig khp &optional iskip))
(defopcode tonex ugen (asig khp &optional inumlayer iskip))
(defopcode trandom ugen (ktrig kmin kmax))
(defopcode tradsyn ugen (fin kscal kpitch kmaxtracks ifn))
(defopcode transeq ugen (ia idur itype ib &rest idur2))
(defopcode transeqb ugen (ia itim itype ib &rest itim2))
(defopcode transeqr ugen (ia idur itype ib &rest idur2))
(defopcode trcross ugen (fin1 fin2 ksearch kdepth &optional kmode))
(defopcode trfilter ugen (fin kamnt ifn))
(defopcode trhighest ugen (fin1 kscal))
(defopcode trigger ugen (ksig kthreshold kmode))
(defopcode trigseq command (ktrig_in kstart kloop kinitndx kfn_values kout1 &rest koutn))
(defopcode trirand ugen (krange))
(defopcode trlowest ugen (fin1 kscal))
(defopcode trmix ugen (fin1 fin2))
(defopcode trscale ugen (fin kpitch &optional kgain))
(defopcode trshift ugen (fin kpshift &optional kgain))
(defopcode trsplit ugen (fin ksplit &optional kgainlow kgainhigh))
(defopcode turnoff command nil)
(defopcode turnoff2 command (kinsno kmode krelease))
(defopcode turnon command (insnum &optional itime))

(defopcode unirand ugen (krange))
(defopcode upsamp ugen (ksig))
(defopcode urandom ugen (imin imax))
(defopcode urd func (xtablenum))

