(in-package :csound)

(defopcode vadd command (ifn kval kelements &optional kdstoffset kverbose))
(defopcode vadd-i command (ifn ival ielements &optional idstoffset) "vadd_i")
(defopcode vaddv command (ifn1 ifn2 kelements &optional kdstoffset ksrcoffset kverbose))
(defopcode vaddv-i command (ifn1 ifn2 ielements &optional idstoffset iscroffset) "vaddv_i")
(defopcode vaget ugen (kndx avar))
(defopcode valpass ugen (asig krvt xlpt imaxlpt &optional iskip insmps))
(defopcode vaset command (kval kndx avar))
(defopcode vbap ugen (asig kazim &optional kelev kspread ilayout))
(defopcode vbapmove ugen (asig idur ispread ifldnum ifld1 &rest ifldn))
(defopcode vbapg ugen (kazim &optional kelev kspread ilayout))
(defopcode vbap16 ugen (asig kazim &optional kelev kspread))
(defopcode vbap16move ugen (asig idur ispread ifldnum ifld1 &rest ifldn))
(defopcode vbap4 ugen (asig kazim &optional kelev kspread))
(defopcode vbap4move ugen (asig idur ispread ifldnum ifld1 &rest ifldn))
(defopcode vbaplsinit command (idim ilsnum &rest idirn))
(defopcode vbapz command (inumchnls istartndx asig kazim &optional kelev kspread))
(defopcode vbapzmove command (inumchnls istartndx asig idur ispread ifldnum ifld1 ifld2 &rest ifldn))
(defopcode vcella command (ktrig kreinit ioutfunc initstatefunc irulefunc ielements irulelen &optional iradius))
(defopcode vco ugen (xamp xcps iwave kpw &optional ifn imaxd ileak inyx iphs iskip))
(defopcode vco2 ugen (kamp kcps &optional imode kpw kphs inyx))
(defopcode vco2ft ugen (kcps iwave &optional inyx))
(defopcode vco2ift ugen (icps iwave &optional inyx))
(defopcode vco2init ugen (iwave &optional ibasfn ipmul iminsiz imaxsiz isrcft))
(defopcode vcomb ugen (asig krvt xlpt imaxlpt &optional iskip insmps))
(defopcode vcopy command (ifn1 ifn2 kelements &optional kdstoffset ksrcoffset kverbose))
(defopcode vcopy-i command (ifn1 ifn2 ielements &optional idstoffset isrcoffset) "vcopy_i")
(defopcode vdelasy ugen (asig adel imaxdel &optional iskip))
(defopcode vdelay3 ugen (asig adel imaxdel &optional iskip))
(defopcode vdelayx ugen (ain adl imd iws &optional ist))
(defopcode vdelayxq ugen (ain1 ain2 ain3 ain4 adl imd iws &optional ist))
(defopcode vdelayxs ugen (ain1 ain2 adl imd iws &optional ist))
(defopcode vdelayxw ugen (ain adl imd iws &optional ist))
(defopcode vdelayxwq ugen (ain1 ain2 ain3 ain4 adl imd iws &optional ist))
(defopcode vdelayxws ugen (ain1 ain2 adl imd iws &optional ist))
(defopcode vdivv command (ifn1 ifn2 kelements &optional kdstoffset ksrcoffset kverbose))
(defopcode vdivv-i command (ifn1 ifn2 ielements &optional idstoffset isrcoffset) "vdivv_i")
(defopcode vdelayk ugen (ksig kdel imaxdel &optional iskip imode))
(defopcode vecdelay ugen (ifn ifnin ifndel ielements imaxdel &optional iskip))
(defopcode vexp command (ifn kval kelements &optional kdstoffset kverbose))
(defopcode vexp-i command (ifn ival ielements &optional idstoffset) "vexp_i")
(defopcode vexpseg command (ifnout ielements ifn1 idur1 ifn2 &rest idur2))
(defopcode vexpv command (ifn1 ifn2 kelements &optional kdstoffset ksrcoffset kverbose))
(defopcode vexpv-i command (ifn1 ifn2 ielements &optional idstoffset isrcoffset) "vexpv_i")
(defopcode vibes ugen (kamp kfreq ihrd ipos imp kvibf kvamp kvibfn idec))
(defopcode vibr ugen (kaverageamp kaveragefreq ifn))
(defopcode vibrato ugen (kaverageamp kaveragefreq krandamountamp krandamountfreq kampminrate kampmaxrate
									 kcpsminrate kcpsmaxrate ifn &optional iphs))
(defopcode vincr command (accum aincr))
(defopcode vlimit command (ifn kmin kmax ielements))
(defopcode vlinseg command (ifnout ielements ifn1 idur1 ifn2 &rest idur2))
(defopcode vlowres ugen (asig kfco kres iord ksep))
(defopcode vmap command (ifn1 ifn2 ielements &optional idstoffset isrcoffset))
(defopcode vmirror command (ifn kmin kmax ielements))
(defopcode vmult command (ifn kval kelements &optional kdstoffset kverbose))
(defopcode vmult-i command (ifn ival ielements &optional idstoffset) "vmult_i")
(defopcode vmultv command (ifn1 ifn2 kelements &optional kdstoffset ksrcoffset kverbose))
(defopcode vmultv-i command (ifn1 ifn2 ielements &optional idstoffset isrcoffset) "vmultv_i")
(defopcode voice ugen (kamp kfreq kphoneme kform kvibf kvamp ifn ivfn))
(defopcode vosim ugen (kamp kfund kform kdecay kpulsecount kpulsefactor ifn &optional iskip))
(defopcode vphaseseg command (kphase ioutab ielems itab1 idist1 itab2 &rest idist2))
(defopcode vport command (ifn khtime ielements &optional ifninit))
(defopcode vpow command (ifn kval kelements &optional kdstoffset kverbose))
(defopcode vpow-i command (ifn ival ielements &optional idstoffset) "vpow_i")
(defopcode vpowv command (ifn1 ifn2 kelements &optional kdstoffset ksrcoffset kverbose))
(defopcode vpowv-i command (ifn1 ifn2 ielements &optional idstoffset isrcoffset) "vpowv_i")
(defopcode vpvoc ugen (ktimpnt kfmod ifile &optional ispecwp ifn))
(defopcode vrandh command (ifn krange kcps ielements &optional idstoffset iseed isize ioffset))
(defopcode vrandi command (ifn krange kcps ielements &optional idstoffset iseed isize ioffset))
(defopcode vsubv command (ifn1 ifn2 kelements &optional kdstoffset ksrcoffset kverbose))
(defopcode vsubv-i command (ifn1 ifn2 ielements &optional idstoffset isrcoffset) "vsubv_i")
(defopcode vtable1k command (kfn kout1 &rest koutn))
(defopcode vtablei command (indx ifn interp ixmode iout1 &rest ioutn))
(defopcode vtablek command (kndx kfn kinterp ixmode kout1 &rest koutn))
(defopcode vtablea command (andx kfn kinterp ixmode aout1 &rest aoutn))
(defopcode vtablewi command (indx ifn ixmode inarg1 &rest inargn))
(defopcode vtablewk command (kndx kfn ixmode knarg1 &rest knargn))
(defopcode vtablewa command (andx kfn ixmode ainarg1 &rest ainargn))
(defopcode vtabi command (indx ifn iout1 &rest ioutn))
(defopcode vtabk command (kndx ifn kout1 &rest koutn))
(defopcode vtaba command (andx ifn aout1 &rest aoutn))
(defopcode vtabwi command (indx ifn inarg1 &rest inargn))
(defopcode vtabwk command (kndx ifn kinarg1 &rest kinargn))
(defopcode vtabwa command (andx ifn ainarg1 &rest ainargn))
(defopcode vwrap command (ifn kmin kmax ielements))
(defopcode waveset ugen (ain krep &optional ilen))
(defopcode weibull ugen (ksigma ktau))
(defopcode wgbow ugen (kamp kfreq kpres krat kvibf kvamp ifn &optional iminfreq))
(defopcode wgbowedbar ugen (kamp kfreq kpos kbowpres kgain &optional iconst itvel ibowpos ilow))
(defopcode wgbrass ugen (kamp kfreq ktens iatt kvibf kvamp ifn &optional iminfreq))
(defopcode wgclar ugen (kamp kfreq kstiff iatt idetk kngain kvibf kvamp ifn &optional iminfreq))
(defopcode wgflute ugen (kamp kfreq kjet iatt idetk kngain kvibf kvamp ifn &optional iminfreq
							  ijetrf iendrf))
(defopcode wgpluck ugen (icps iamp kpick iplk idamp ifilt axcite))
(defopcode wgpluck2 ugen (iplk kamp icps kpick krefl))
(defopcode wguide1 ugen (asig xfreq kcutoff kfeedback))
(defopcode wguide2 ugen (asig xfreq1 xfreq2 kcutoff1 kcutoff2 kfeedback1 kfeedback2))
(defopcode wrap ugen (xsig klow khigh))
(defopcode wterrain ugen (kamp kpch k_xcenter k_ycenter k_xradius k_yradius itabx itaby))
(defopcode xadsr ugen (iatt idec islev irel &optional idel))

(defopcode xscanmap ugen (iscan kamp kvamp &optional iwhich))
(defopcode xscansmap command (kpos kvel iscan kamp kvamp &optional iwhich))
(defopcode xscans ugen (kamp kfreq ifntraj id &optional iorder))
(defopcode xscanu command (init irate ifnvel ifnmass ifnstif ifncentr ifndamp kmas
								kstif kcentr kdamp ileft iright kpos kstrngth ain idisp id))
(defopcode xtratim command (iextradur))
(defopcode xyin ugen (iprd ixmin ixmax iymin iymax &optional ixinit iyinit))

(defopcode zacl command (kfirst klast))
(defopcode zakinit command (isizea isizek))
(defopcode zamod ugen (asig kzamod))
(defopcode zar ugen (kndx))
(defopcode zarg ugen (kndx kgain))
(defopcode zaw command (asig kndx))
(defopcode zawm command (asig kndx &optional imix))
(defopcode zfilter2 ugen (asig kdamp kfreq im in ib0 ib1 &rest rest))
(defopcode zir ugen (indx))
(defopcode ziw command (isig indx))
(defopcode ziwm command (isig indx &optional imix))
(defopcode zkcl command (kfirst klast))
(defopcode zkmod ugen (ksig kzkmod))
(defopcode zkr ugen (kndx))
(defopcode zkw command (ksig kndx))
(defopcode zkwm command (ksig kndx &optional imix))

